ProjektASP/ProjektASP/Controllers/MarksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjektASP.Models;

namespace ProjektASP.Controllers
{
    public class MarksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Marks
        public ActionResult Index()
        {
            var marks = db.Marks.Include(m => m.StudentModel).Include(m => m.SubjectModel);
            return View(marks.ToList());
        }

        // GET: Marks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mark mark = db.Marks.Find(id);
            if (mark == null)
            {
                return HttpNotFound();
            }
            return View(mark);
        }

        // GET: Marks/Create
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult Create()
        {
            ViewBag.StudentID = new SelectList(db.StudentModels, "StudentID", "Name");
            ViewBag.SubjectID = new SelectList(db.SubjectModels, "SubjectID", "Name");
            return View();
        }

        // POST: Marks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult Create([Bind(Include = "MarkID,MarkNum,StudentID,SubjectID")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                db.Marks.Add(mark);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentID = new SelectList(db.StudentModels, "StudentID", "Name", mark.StudentID);
            ViewBag.SubjectID = new SelectList(db.SubjectModels, "SubjectID", "Name", mark.SubjectID);
            return View(mark);
        }

        // GET: Marks/Edit/5
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mark mark = db.Marks.Find(id);
            if (mark == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentID = new SelectList(db.StudentModels, "StudentID", "Name", mark.StudentID);
            ViewBag.SubjectID = new SelectList(db.SubjectModels, "SubjectID", "Name", mark.SubjectID);
            return View(mark);
        }

        // POST: Marks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult Edit([Bind(Include = "MarkID,MarkNum,StudentID,SubjectID")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mark).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StudentID = new SelectList(db.StudentModels, "StudentID", "Name", mark.StudentID);
            ViewBag.SubjectID = new SelectList(db.SubjectModels, "SubjectID", "Name", mark.SubjectID);
            return View(mark);
        }

        // GET: Marks/Delete/5
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mark mark = db.Marks.Find(id);
            if (mark == null)
            {
                return HttpNotFound();
            }
            return View(mark);
        }

        // POST: Marks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Nauczyciel")]
        public ActionResult DeleteConfirmed(int id)
        {
            Mark mark = db.Marks.Find(id);
            db.Marks.Remove(mark);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjektASP/ProjektASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Strona główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>,
                    <li>@Html.ActionLink("Oceny", "Index", "Marks")</li>
                    <li>@Html.ActionLink("Studenci", "Index", "StudentModels")</li>
                    <li>@Html.ActionLink("Api", "Api", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @ViewBag.Title</p>
            <p>Liczba odwiedzin strony: @ApplicationInstance.Application["Visited"] </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjektASP/ProjektASP/Views/Shared/_NewestStudent.cshtml
@model IEnumerable<ProjektASP.Models.StudentModel>

<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-center">Imię</th>
            <th class="text-center">Nazwisko</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="row text-center">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="row text-center">
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
            </tr>
        }
    </tbody>
</table>

ProjektASP/ProjektASP/Views/Shared/_Teacher.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Strona Główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Ban", "", "Ban")</li>,
                    <li>@Html.ActionLink("Oceny", "Index", "Marks")</li>
                    <li>@Html.ActionLink("Studenci", "Index", "StudentModels")</li>
                    <li>@Html.ActionLink("Api", "Api", "Home")</li>
                    <li>@Html.ActionLink("Dodaj przedmiot", "Create", "SubjectModels")</li>
                    <li>@Html.ActionLink("Dodaj ocene", "Create", "Marks")</li>
                    <li>@Html.ActionLink("Dodaj studenta", "Create", "StudentModels")</li>
</ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @ViewBag.Title</p>
            <p>Liczba odwiedzin strony: @ApplicationInstance.Application["Visited"] </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>